name: Docker CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
         # Add more steps here
      - name: Login to GitHub Container Registry
        uses: docker login  -u plamengerchev
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build
        uses: docker/login-action@v3
        with:
          context: exercise_3
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest     
          

  # More jobs can be added
